spring.datasource.url=jdbc:h2:mem:hireconnect_job_test;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

eureka.client.enabled=false
app.security.enabled=false
app.security.jwt.issuer=hireconnect-auth-service
app.security.jwt.secret=VGhpc0lzQVRlc3RTZWNyZXRGb3JBdXRoU2VydmljZUxvY2FsRGV2T25seTEyMzQ1Njc4OTAxMjM0NTY=
app.services.profile.base-url=http://localhost:8084
