spring.application.name=eureka-service

server.port=${SERVER_PORT:8761}

eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
spring.cloud.service-registry.auto-registration.enabled=false
eureka.server.enable-self-preservation=false
eureka.server.wait-time-in-ms-when-sync-empty=0

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
