spring.datasource.url=jdbc:h2:mem:hireconnect_profile_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop

eureka.client.enabled=false
spring.cloud.discovery.enabled=false
app.security.enabled=false
app.security.jwt.issuer=hireconnect-auth-service
app.security.jwt.secret=VGhpc0lzQVRlc3RTZWNyZXRGb3JBdXRoU2VydmljZUxvY2FsRGV2T25seTEyMzQ1Njc4OTAxMjM0NTY=
